# Welcome to Jekyll!

title: Агентство Рейл Консалт
email:
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
twitter_username: username
github_username: username
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Рейл Консалт"
  avatar : "/assets/images/favicon.ico"
  bio    : "Свобода для дела"
  location : "Россия, Екатеринбург"
  links:
    - label: "История возниконовения"
      icon: "fas fa-fw fa-link"
      url: "https://arctl.github.io/railconsult/history/"
    - label: "Наше предназначение"
      icon: "fas fa-fw fa-link"
      url: "https://arctl.github.io/railconsult/destiny/"
    - label: "Кто наши клиенты"
      icon: "fas fa-fw fa-link"
      url: "https://arctl.github.io/railconsult/clients/"
    - label: "Запрос на подключение"
      icon: "fas fa-edit"
      url: "https://arctl.ru/contact-us/?theme=Запрос%20на%20подключение"

footer:
  links:
    - label: "facebook"
      icon: "fab fa-fw fa-facebook"
      url: "https://web.facebook.com/arctlonline"
    - label: "telegramm"
      icon: "fab fa-telegram"
      url: "https://t.me/arctl"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /about/
tag_archive:
  type: liquid
  path: /tags/
